name: DVC Pull
description: Setup DVC and pull test data from public Cloudflare R2

runs:
  using: composite
  steps:
    - name: ⚙️ DVC setup
      uses: iterative/setup-dvc@6c05772f52d19792ed73aedb6c2bf65ec92adebb # v3.0.0
    - name: 🗄️ DVC pull
      shell: bash
      run: dvc pull
