name: Bump Version

on:
  workflow_call:
    inputs:
      pkg_name:
        required: true
        type: string
      pkg_version:
        required: true
        type: string
      dir_conda_env_yaml:
        required: false
        type: string
        default: deploy/conda/env/yaml
      dvc:
        required: false
        type: boolean
        default: false

jobs:
  bump:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      contents: write
    steps:
      - name: 🤖 App token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.BOT1_APP_ID }}
          private-key: ${{ secrets.BOT1_APP_PRIVATE_KEY }}
      - name: 🚚 Codeout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: 👾 Miniforge setup
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          auto-update-conda: true
          environment-file: ${{ inputs.dir_conda_env_yaml }}/bump.yaml
          activate-environment: bump_env
          miniforge-version: 26.1.0-0 # need to use mamba < 2.6.0 - see conda/conda-lock#906
      - name: ⚙️ DVC setup
        if: inputs.dvc == true
        uses: iterative/setup-dvc@4bdfd2b0f6f1ad7e08afadb03b1a895c352a5239 # v2.0.0
      - name: 🗄️ DVC pull
        if: inputs.dvc == true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_REGION: auto
        run: |
          dvc pull
          ls -l inst/extdata/*
      - name: 🔖 Bump version
        env:
          APP_ID: ${{ vars.BOT1_APP_ID }}
          INPUTS_PKG_VERSION: ${{ inputs.pkg_version }}
        run: |
          git config --local user.email "${APP_ID}+tidywf-ci-bot[bot]@users.noreply.github.com"
          git config --local user.name "tidywf-ci-bot[bot]"
          echo "OLD_VERSION=$(grep '^Version:' DESCRIPTION | awk '{print $2}')" >> $GITHUB_ENV
          bump-my-version bump --new-version ${INPUTS_PKG_VERSION} --no-commit
      - name: 📦 Install from source
        run: R CMD INSTALL --no-test-load .
      - name: 📖 Render README
        run: quarto render README.qmd
      - name: 💾 Commit and push
        env:
          INPUTS_PKG_VERSION: ${{ inputs.pkg_version }}
        run: |
          git add .
          git commit -m "Bump version: ${OLD_VERSION} => ${INPUTS_PKG_VERSION}"
          git pull --rebase
          git push
