name: Conda Deploy

on:
  workflow_call:
    inputs:
      pkg_name:
        required: true
        type: string
      pkg_version:
        required: true
        type: string
      conda_org:
        required: false
        type: string
        default: tidywf
      dir_conda_recipe:
        required: false
        type: string
        default: deploy/conda/recipe
      dir_conda_env_yaml:
        required: false
        type: string
        default: deploy/conda/env/yaml
      dir_conda_env_lock:
        required: false
        type: string
        default: deploy/conda/env/lock

jobs:
  conda_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      contents: write

    steps:
      - name: 🤖 App token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token1
        with:
          client-id: ${{ vars.BOT1_APP_ID }}
          private-key: ${{ secrets.BOT1_APP_PRIVATE_KEY }}
      - name: 🚚 Codeout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token1.outputs.token }} # branch write override
      - name: 👾 Miniforge setup
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          auto-update-conda: true
          environment-file: ${{ inputs.dir_conda_env_yaml }}/condabuild.yaml
          activate-environment: condabuild_env
          miniforge-version: 26.1.0-0 # need to use mamba < 2.6.0 - see conda/conda-lock#906
      - name: 🐍 Conda pkg build
        run: |
          EXTRA_CHANNEL=""
          [[ "${GITHUB_REF}" == "refs/heads/dev" ]] && EXTRA_CHANNEL="--channel ${INPUTS_CONDA_ORG}/label/dev"
          rattler-build build \
            ${EXTRA_CHANNEL} \
            --channel ${INPUTS_CONDA_ORG} \
            --channel conda-forge \
            --recipe ${INPUTS_DIR_CONDA_RECIPE}/recipe.yaml \
            --output-dir ${RUNNER_TEMP}/out1
        env:
          INPUTS_CONDA_ORG: ${{ inputs.conda_org }}
          INPUTS_DIR_CONDA_RECIPE: ${{ inputs.dir_conda_recipe }}
      - name: 🐍 Conda pkg upload
        run: |
          pkg_path=$(find ${RUNNER_TEMP}/out1 -type f -name "*.conda")
          LABEL_ARG=""
          [[ "${GITHUB_REF}" == "refs/heads/dev" ]] && LABEL_ARG="--channel dev"
          rattler-build upload anaconda \
            --owner ${INPUTS_CONDA_ORG} \
            --api-key ${{ secrets.ANACONDA_UPLOAD_TOKEN }} \
            ${LABEL_ARG} \
            ${pkg_path}
        env:
          INPUTS_CONDA_ORG: ${{ inputs.conda_org }}
      - name: 🔒 Conda lock
        run: |
          CHANNEL_ARGS="--channel ${INPUTS_CONDA_ORG} --channel conda-forge"
          [[ "${GITHUB_REF}" == "refs/heads/dev" ]] && CHANNEL_ARGS="--channel ${INPUTS_CONDA_ORG}/label/dev ${CHANNEL_ARGS}"
          conda-lock lock \
            --file ${INPUTS_DIR_CONDA_ENV_YAML}/${INPUTS_PKG_NAME}.yaml \
            ${CHANNEL_ARGS} \
            -p linux-64
          conda-lock render \
            -p linux-64 \
            conda-lock.yml \
          && rm conda-lock.yml \
          && mv conda-linux-64.lock ${INPUTS_DIR_CONDA_ENV_LOCK}/
        env:
          INPUTS_CONDA_ORG: ${{ inputs.conda_org }}
          INPUTS_DIR_CONDA_ENV_YAML: ${{ inputs.dir_conda_env_yaml }}
          INPUTS_PKG_NAME: ${{ inputs.pkg_name }}
          INPUTS_DIR_CONDA_ENV_LOCK: ${{ inputs.dir_conda_env_lock }}
      - name: 💾 Commit lockfiles
        env:
          APP_ID: ${{ vars.BOT1_APP_ID }}
          INPUTS_PKG_VERSION: ${{ inputs.pkg_version }}
        run: |
          git config --local user.email "${APP_ID}+tidywf-ci-bot[bot]@users.noreply.github.com"
          git config --local user.name "tidywf-ci-bot[bot]"
          git add .
          git commit -m "[bot] Updating conda-lock files (v${INPUTS_PKG_VERSION})"
          git pull --rebase # to pull in umlise commit
          git push
