name: UML Deploy

on:
  workflow_call:
    inputs:
      dir_conda_env_yaml:
        required: false
        type: string
        default: deploy/conda/env/yaml

jobs:
  uml:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      contents: write

    steps:
      - name: 🤖 App token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token-uml
        with:
          client-id: ${{ vars.BOT1_APP_ID }}
          private-key: ${{ secrets.BOT1_APP_PRIVATE_KEY }}
      - name: 🚚 Codeout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token-uml.outputs.token }}
      - name: 👾 Miniforge setup
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          auto-update-conda: true
          environment-file: ${{ inputs.dir_conda_env_yaml }}/uml.yaml
          activate-environment: uml_env
          miniforge-version: 26.1.0-0 # need to use mamba < 2.6.0 - see conda/conda-lock#906
      - name: 📦 Install from source
        run: R CMD INSTALL --no-test-load .
      - name: 🎨 Generate UML diagram
        run: Rscript inst/scripts/uml.R
      - name: 💾 Commit UML files
        env:
          APP_ID: ${{ vars.BOT1_APP_ID }}
        run: |
          git config --local user.email "${APP_ID}+tidywf-ci-bot[bot]@users.noreply.github.com"
          git config --local user.name "tidywf-ci-bot[bot]"
          git add vignettes/fig/uml/
          git diff --staged --quiet || (git commit -m "[bot] Update UML diagram" && git push)
